manifest_version = 2
name = "Add a new field to a JSON response"
description = ""
authors = ["<oss@fastly.com>"]
language = "javascript"
service_id = "3e9ZvP4gepxSEcp1NeNphE"

[local_server.backends.origin_0]
  url = "https://mock.edgecompute.app"

[setup.backends.origin_0]
address = "mock.edgecompute.app"
port = 443
